name = "user-management-frontend"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[env.production]
name = "user-management-frontend"

[env.preview]
name = "user-management-frontend-preview"

# Environment variables for frontend
[vars]
VITE_API_URL = "https://user-management-backend.your-subdomain.workers.dev"