# Cloudflare Pages配置文件
[build]
  command = "cd ../frontend && npm install && npm run build"
  publish = "../frontend/dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# 环境变量配置
[env.production.vars]
  VITE_API_URL = "https://email-backend-worker.your-subdomain.workers.dev"
  VITE_APP_NAME = "User Management System"
  VITE_APP_VERSION = "1.0.0"

[env.preview.vars]
  VITE_API_URL = "https://email-backend-worker.your-subdomain.workers.dev"
  VITE_APP_NAME = "User Management System (Preview)"
  VITE_APP_VERSION = "1.0.0-preview"

# 重定向规则
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 头部配置
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"