# Cloudflare Workers配置文件
name = "email-backend-worker"
main = "worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# 环境配置
[env.production]
name = "email-backend-worker"
vars = { NODE_ENV = "production", PORT = "8787", API_PREFIX = "api" }

# KV命名空间 (可选)
# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "your-kv-namespace-id"
# preview_id = "your-preview-kv-namespace-id"

# D1数据库 (可选)
# [[d1_databases]]
# binding = "DB"
# database_name = "user-management-db"
# database_id = "your-d1-database-id"

# R2存储桶 (可选)
# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "your-r2-bucket"

# 环境变量 (非敏感信息)
[vars]
NODE_ENV = "production"
PORT = "8787"
API_PREFIX = "api"
BCRYPT_ROUNDS = "12"
EMAIL_CODE_EXPIRES_IN = "300"
RATE_LIMIT_TTL = "60"
RATE_LIMIT_LIMIT = "100"
JWT_EXPIRES_IN = "1h"
JWT_REFRESH_EXPIRES_IN = "7d"
SENDGRID_FROM_EMAIL = "1801273437@qq.com"

# 注意: 敏感信息应使用 wrangler secret put 命令设置:
# wrangler secret put JWT_SECRET
# wrangler secret put JWT_REFRESH_SECRET
# wrangler secret put DB_HOST
# wrangler secret put DB_USERNAME
# wrangler secret put DB_PASSWORD
# wrangler secret put SENDGRID_API_KEY
# wrangler secret put REDIS_PASSWORD